-- Persistência do API Engine Monitor.
--
-- O painel administrativo precisa sobreviver a reloads, troca de sessão e nova
-- abertura do admin, então cada chamada externa registrada pelo engine logger
-- passa a ser gravada no banco e consultada em janela móvel de 24h.

CREATE TABLE IF NOT EXISTS public.engine_api_call_logs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts            timestamptz NOT NULL DEFAULT now(),
  api           text        NOT NULL CHECK (api IN ('tmdb', 'omdb', 'watchmode', 'motn')),
  op            text        NOT NULL,
  origin        text        NOT NULL,
  media_type    text        CHECK (media_type IN ('movie', 'tv')),
  tmdb_id       integer,
  endpoint      text,
  cache_status  text        NOT NULL CHECK (cache_status IN ('hit', 'miss', 'stale', 'forced', 'failed', 'skipped', 'none')),
  duration_ms   integer     NOT NULL CHECK (duration_ms >= 0),
  success       boolean     NOT NULL,
  http_status   integer,
  error         text,
  fallback_from text        CHECK (fallback_from IN ('tmdb', 'omdb', 'watchmode', 'motn')),
  created_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.engine_api_call_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service role manages engine_api_call_logs"
  ON public.engine_api_call_logs
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS engine_api_call_logs_ts_idx
  ON public.engine_api_call_logs (ts DESC);

CREATE INDEX IF NOT EXISTS engine_api_call_logs_api_ts_idx
  ON public.engine_api_call_logs (api, ts DESC);

CREATE INDEX IF NOT EXISTS engine_api_call_logs_origin_ts_idx
  ON public.engine_api_call_logs (origin, ts DESC);

CREATE OR REPLACE FUNCTION public.engine_api_call_log_stats(
  p_since timestamptz DEFAULT now() - interval '24 hours'
)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public
AS $$
WITH api_names(api) AS (
  VALUES ('tmdb'), ('omdb'), ('watchmode'), ('motn')
),
filtered AS (
  SELECT *
  FROM public.engine_api_call_logs
  WHERE ts >= p_since
),
totals AS (
  SELECT
    count(*)::int AS total_calls,
    count(*) FILTER (WHERE cache_status = 'hit')::int AS total_hits,
    min(ts) AS started_at
  FROM filtered
),
per_api_rows AS (
  SELECT
    api_names.api,
    count(filtered.id)::int AS calls,
    count(filtered.id) FILTER (WHERE filtered.cache_status = 'hit')::int AS hits,
    count(filtered.id) FILTER (WHERE NOT filtered.success)::int AS errors,
    coalesce(round(avg(filtered.duration_ms))::int, 0) AS avg_ms,
    coalesce(max(filtered.duration_ms), 0)::int AS max_ms,
    coalesce(
      percentile_disc(0.95) WITHIN GROUP (ORDER BY filtered.duration_ms),
      0
    )::int AS p95_ms
  FROM api_names
  LEFT JOIN filtered ON filtered.api = api_names.api
  GROUP BY api_names.api
),
per_api AS (
  SELECT jsonb_object_agg(
    api,
    jsonb_build_object(
      'calls', calls,
      'hits', hits,
      'misses', greatest(0, calls - hits - errors),
      'errors', errors,
      'avgMs', avg_ms,
      'maxMs', max_ms,
      'p95Ms', p95_ms,
      'hitRate', CASE WHEN calls > 0 THEN round((hits::numeric / calls) * 100)::int ELSE 0 END
    )
  ) AS payload
  FROM per_api_rows
),
per_origin AS (
  SELECT coalesce(jsonb_object_agg(origin, calls ORDER BY calls DESC), '{}'::jsonb) AS payload
  FROM (
    SELECT origin, count(*)::int AS calls
    FROM filtered
    GROUP BY origin
    ORDER BY calls DESC, origin ASC
  ) origins
)
SELECT jsonb_build_object(
  'summary', jsonb_build_object(
    'startedAt', coalesce((SELECT started_at FROM totals), now()),
    'uptimeMs', floor(extract(epoch FROM (now() - coalesce((SELECT started_at FROM totals), now()))) * 1000)::bigint,
    'totalCalls', (SELECT total_calls FROM totals),
    'cacheHitRate', CASE
      WHEN (SELECT total_calls FROM totals) > 0
        THEN round(((SELECT total_hits FROM totals)::numeric / (SELECT total_calls FROM totals)) * 100)::int
      ELSE 0
    END
  ),
  'perApi', (SELECT payload FROM per_api),
  'perOrigin', (SELECT payload FROM per_origin)
);
$$;

REVOKE ALL ON FUNCTION public.engine_api_call_log_stats(timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.engine_api_call_log_stats(timestamptz) FROM anon;
REVOKE ALL ON FUNCTION public.engine_api_call_log_stats(timestamptz) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.engine_api_call_log_stats(timestamptz) TO service_role;
